[hugoVersion]
    extended = true

mounts = [
    {target="content", source="content"},
    {target="content", source="../../content"},
    {target="assets", source="assets"},
    {target="assets", source="../../assets"},
    {target="static", source="static"},
    {target="data", source="data"},
    {target="i18n", source="i18n"},
    {target="archetypes", source="archetypes"},
    {target="layouts", source="layouts"},
]

# ----------------------------------------------------------------------
# Notes:
# - Some "source" directories are outside/above the Hugo root directory
#   so that they are safely away from "dangerous" files that should not
#   be touched by (non-technical) editors.
