[hugoVersion]
    extended = true

# ---- Mounts with both "editor-safe" and "developer" directories
[[mounts]]
source = 'content'
target = 'content'
[[mounts]]
source = '../../content'
target = 'content'
[[mounts]]
source = 'assets'
target = 'assets'
[[mounts]]
source = '../../assets'
target = 'assets'

# ---- Mounts with "developer" directories only
[[mounts]]
source = 'static'
target = 'static'
[[mounts]]
source = 'data'
target = 'data'
[[mounts]]
source = 'i18n'
target = 'i18n'
[[mounts]]
source = 'archetypes'
target = 'archetypes'
[[mounts]]
source = 'layouts'
target = 'layouts'


# ----------------------------------------------------------------------
# Notes:
# - Some "source" directories are outside/above the Hugo root directory
#   so that they are safely away from "dangerous" files that should not
#   be touched by (non-technical) editors.
